name: Build

on:
  - push

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

      - name: '[BUILD] | Install Dependencies'
        run: make download
        shell: bash

      - name: '[BUILD] | Compile'
        run: make build
        shell: bash

      - name: '[TEST] | Lint Check'
        run: make lint
        shell: bash
